#!/usr/bin/env bash
# Print string best school except line 4 & 8
i=1
while [ $((i++)) -le 9 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
